ISSUE_CODE_MAP = {
    "ACC": "Accounting",
    "ADV": "Advertising",
    "AER": "Aerospace",
    "AGR": "Agriculture",
    "ALC": "Alcohol & Drug Abuse",
    "ANI": "Animals",
    "APP": "Apparel/Clothing Industry/Textiles",
    "ART": "Arts/Entertainment",
    "AUT": "Automotive Industry",
    "AVI": "Aviation/Aircraft/Airlines",
    "BUD": "Budget/Appropriations",
    "CHM": "Chemicals/Chemical Industry",
    "CIV": "Civil Rights/Civil Liberties",
    "COM": "Communications/Broadcasting/Radio/TV",
    "CPI": "Consumer Product Safety",
    "CPT": "Computers/Information Technology",
    "DEF": "Defense",
    "DOC": "District of Columbia",
    "ECN": "Economics/Economic Development",
    "EDU": "Education",
    "ENG": "Energy/Nuclear",
    "ENV": "Environment/Superfund",
    "FIN": "Financial Institutions/Investments/Securities",
    "FOO": "Food Industry",
    "FOR": "Foreign Relations",
    "FUE": "Fuel/Gas/Oil",
    "GAM": "Gaming/Gambling/Casino",
    "GOV": "Government Issues",
    "HCR": "Health Issues",
    "HOM": "Homeland Security",
    "HOU": "Housing",
    "IMM": "Immigration",
    "IND": "Indian/Native American Affairs",
    "INS": "Insurance",
    "INT": "Intelligence and Surveillance",
    "LBR": "Labor Issues/Antitrust/Workplace",
    "LAW": "Law Enforcement/Crime/Criminal Justice",
    "MAN": "Manufacturing",
    "MAR": "Marine/Maritime/Boating/Fisheries",
    "MED": "Medical/Disease Research/Clinical Labs",
    "MMM": "Medicare/Medicaid",
    "MON": "Minting/Money/Gold Standard",
    "NAT": "Natural Resources",
    "PHA": "Pharmacy",
    "POS": "Postal",
    "REL": "Religion",
    "RES": "Real Estate/Land Use/Conservation",
    "RET": "Retail Sales",
    "ROD": "Roads/Highway",
    "SCI": "Science/Technology",
    "SMB": "Small Business",
    "SPO": "Sports/Athletics",
    "TAX": "Taxation/Internal Revenue Code",
    "TEC": "Telecommunications",
    "TOB": "Tobacco",
    "TOR": "Torts",
    "TOU": "Travel/Tourism",
    "TRA": "Transportation",
    "TRD": "Trade",
    "URB": "Urban Development/Municipalities",
    "UTI": "Utilities",
    "VET": "Veterans",
    "WAS": "Waste",
    "WEL": "Welfare",
}